site_name: My Docs
theme: 
  name: material
site_url: https://ken0yuan.github.io/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences